
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: gcr.io/pivotal-purpose-311120/test-image:latest
        name: test-image
      imagePullSecrets:
        - name: gcr-json-key